name = "docs-engine-example"
type = "webpack"
account_id = "1e1395dd88464c726799aac6c1be4a71" # adam.workers.dev
workers_dev = true

[site]
bucket = ".docsengine/docs-engine/public/workers" # TODO: support non-`/workers` pathPrefix
entry-point = ".docsengine/docs-engine/workers-site"
